name = "Cobblemon Pack"
author = "Markflynnman"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1de7571ef7e7fda561b7544f62fd9f543a7a87e960d83e9b2bed3863f2386b7a"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
acceptable-game-versions = []
datapack-folder = "global_packs/required_data"
