name = "Cobblemon Pack"
author = "Markflynnman"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2b473f1fa9649400ebc7b557f4e0969775d04254af97643adc831b2a4cb59f7"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
