Platform.mods.kubejs.name = 'Markflynnman'

StartupEvents.registry('item', event => {
    // Indigo League
    event.create('boulder_badge')
    .texture('kubejs:item/indigo/boulder_badge')
    .displayName('Boulder Badge')
    .tooltip('Indigo League')
    .unstackable()
    .fireResistant(true)

    event.create('cascade_badge')
    .texture('kubejs:item/indigo/cascade_badge')
    .displayName('Cascade Badge')
    .tooltip('Indigo League')
    .unstackable()
    .fireResistant(true)

    event.create('thunder_badge')
    .texture('kubejs:item/indigo/thunder_badge')
    .displayName('Thunder Badge')
    .tooltip('Indigo League')
    .unstackable()
    .fireResistant(true)

    event.create('rainbow_badge')
    .texture('kubejs:item/indigo/rainbow_badge')
    .displayName('Rainbow Badge')
    .tooltip('Indigo League')
    .unstackable()
    .fireResistant(true)

    event.create('soul_badge')
    .texture('kubejs:item/indigo/soul_badge')
    .displayName('Soul Badge')
    .tooltip('Indigo League')
    .unstackable()
    .fireResistant(true)

    event.create('marsh_badge')
    .texture('kubejs:item/indigo/marsh_badge')
    .displayName('Marsh Badge')
    .tooltip('Indigo League')
    .unstackable()
    .fireResistant(true)

    event.create('volcano_badge')
    .texture('kubejs:item/indigo/volcano_badge')
    .displayName('Volcano Badge')
    .tooltip('Indigo League')
    .unstackable()
    .fireResistant(true)

    event.create('earth_badge')
    .texture('kubejs:item/indigo/earth_badge')
    .displayName('Earth Badge')
    .tooltip('Indigo League')
    .unstackable()
    .fireResistant(true)

    // Johto League
    event.create('zephyr_badge')
    .texture('kubejs:item/johto/zephyr_badge')
    .displayName('Zephyr Badge')
    .tooltip('Johto League')
    .unstackable()
    .fireResistant(true)

    event.create('hive_badge')
    .texture('kubejs:item/johto/hive_badge')
    .displayName('Hive Badge')
    .tooltip('Johto League')
    .unstackable()
    .fireResistant(true)

    event.create('plain_badge')
    .texture('kubejs:item/johto/plain_badge')
    .displayName('Plain Badge')
    .tooltip('Johto League')
    .unstackable()
    .fireResistant(true)

    event.create('fog_badge')
    .texture('kubejs:item/johto/fog_badge')
    .displayName('Fog Badge')
    .tooltip('Johto League')
    .unstackable()
    .fireResistant(true)

    event.create('storm_badge')
    .texture('kubejs:item/johto/storm_badge')
    .displayName('Storm Badge')
    .tooltip('Johto League')
    .unstackable()
    .fireResistant(true)

    event.create('mineral_badge')
    .texture('kubejs:item/johto/mineral_badge')
    .displayName('Mineral Badge')
    .tooltip('Johto League')
    .unstackable()
    .fireResistant(true)

    event.create('glacier_badge')
    .texture('kubejs:item/johto/glacier_badge')
    .displayName('Glacier Badge')
    .tooltip('Johto League')
    .unstackable()
    .fireResistant(true)

    event.create('rising_badge')
    .texture('kubejs:item/johto/rising_badge')
    .displayName('Rising Badge')
    .tooltip('Johto League')
    .unstackable()
    .fireResistant(true)

    // Hoenn League
    event.create('stone_badge')
    .texture('kubejs:item/hoenn/stone_badge')
    .displayName('Stone Badge')
    .tooltip('Hoenn League')
    .unstackable()
    .fireResistant(true)

    event.create('knuckle_badge')
    .texture('kubejs:item/hoenn/knuckle_badge')
    .displayName('Knuckle Badge')
    .tooltip('Hoenn League')
    .unstackable()
    .fireResistant(true)

    event.create('dynamo_badge')
    .texture('kubejs:item/hoenn/dynamo_badge')
    .displayName('Dynamo Badge')
    .tooltip('Hoenn League')
    .unstackable()
    .fireResistant(true)

    event.create('heat_badge')
    .texture('kubejs:item/hoenn/heat_badge')
    .displayName('Heat Badge')
    .tooltip('Hoenn League')
    .unstackable()
    .fireResistant(true)

    event.create('balance_badge')
    .texture('kubejs:item/hoenn/balance_badge')
    .displayName('Balance Badge')
    .tooltip('Hoenn League')
    .unstackable()
    .fireResistant(true)

    event.create('feather_badge')
    .texture('kubejs:item/hoenn/feather_badge')
    .displayName('Feather Badge')
    .tooltip('Hoenn League')
    .unstackable()
    .fireResistant(true)

    event.create('mind_badge')
    .texture('kubejs:item/hoenn/mind_badge')
    .displayName('Mind Badge')
    .tooltip('Hoenn League')
    .unstackable()
    .fireResistant(true)

    event.create('rain_badge')
    .texture('kubejs:item/hoenn/rain_badge')
    .displayName('Rain Badge')
    .tooltip('Hoenn League')
    .unstackable()
    .fireResistant(true)

    // Sinnoh League
    event.create('coal_badge')
    .texture('kubejs:item/sinnoh/coal_badge')
    .displayName('Coal Badge')
    .tooltip('Sinnoh League')
    .unstackable()
    .fireResistant(true)

    event.create('forest_badge')
    .texture('kubejs:item/sinnoh/forest_badge')
    .displayName('Forest Badge')
    .tooltip('Sinnoh League')
    .unstackable()
    .fireResistant(true)

    event.create('cobble_badge')
    .texture('kubejs:item/sinnoh/cobble_badge')
    .displayName('Cobble Badge')
    .tooltip('Sinnoh League')
    .unstackable()
    .fireResistant(true)

    event.create('fen_badge')
    .texture('kubejs:item/sinnoh/fen_badge')
    .displayName('Fen Badge')
    .tooltip('Sinnoh League')
    .unstackable()
    .fireResistant(true)

    event.create('relic_badge')
    .texture('kubejs:item/sinnoh/relic_badge')
    .displayName('Relic Badge')
    .tooltip('Sinnoh League')
    .unstackable()
    .fireResistant(true)

    event.create('mine_badge')
    .texture('kubejs:item/sinnoh/mine_badge')
    .displayName('Mine Badge')
    .tooltip('Sinnoh League')
    .unstackable()
    .fireResistant(true)

    event.create('icicle_badge')
    .texture('kubejs:item/sinnoh/icicle_badge')
    .displayName('Icicle Badge')
    .tooltip('Sinnoh League')
    .unstackable()
    .fireResistant(true)

    event.create('beacon_badge')
    .texture('kubejs:item/sinnoh/beacon_badge')
    .displayName('Beacon Badge')
    .tooltip('Sinnoh League')
    .unstackable()
    .fireResistant(true)

    // Unova League
    event.create('trio_badge')
    .texture('kubejs:item/unova/trio_badge')
    .displayName('Trio Badge')
    .tooltip('Unova League')
    .unstackable()
    .fireResistant(true)

    event.create('basic_badge')
    .texture('kubejs:item/unova/basic_badge')
    .displayName('Basic Badge')
    .tooltip('Unova League')
    .unstackable()
    .fireResistant(true)

    event.create('toxic_badge')
    .texture('kubejs:item/unova/toxic_badge')
    .displayName('Toxic Badge')
    .tooltip('Unova League')
    .unstackable()
    .fireResistant(true)

    event.create('insect_badge')
    .texture('kubejs:item/unova/insect_badge')
    .displayName('Insect Badge')
    .tooltip('Unova League')
    .unstackable()
    .fireResistant(true)

    event.create('bolt_badge')
    .texture('kubejs:item/unova/bolt_badge')
    .displayName('Bolt Badge')
    .tooltip('Unova League')
    .unstackable()
    .fireResistant(true)

    event.create('quake_badge')
    .texture('kubejs:item/unova/quake_badge')
    .displayName('Quake Badge')
    .tooltip('Unova League')
    .unstackable()
    .fireResistant(true)

    event.create('jet_badge')
    .texture('kubejs:item/unova/jet_badge')
    .displayName('Jet Badge')
    .tooltip('Unova League')
    .unstackable()
    .fireResistant(true)

    event.create('freeze_badge')
    .texture('kubejs:item/unova/freeze_badge')
    .displayName('Freeze Badge')
    .tooltip('Unova League')
    .unstackable()
    .fireResistant(true)

    event.create('legend_badge')
    .texture('kubejs:item/unova/legend_badge')
    .displayName('Legend Badge')
    .tooltip('Unova League')
    .unstackable()
    .fireResistant(true)

    event.create('wave_badge')
    .texture('kubejs:item/unova/wave_badge')
    .displayName('Wave Badge')
    .tooltip('Unova League')
    .unstackable()
    .fireResistant(true)

    // Kalos League
    event.create('bug_badge')
    .texture('kubejs:item/kalos/bug_badge')
    .displayName('Bug Badge')
    .tooltip('Kalos League')
    .unstackable()
    .fireResistant(true)

    event.create('cliff_badge')
    .texture('kubejs:item/kalos/cliff_badge')
    .displayName('Cliff Badge')
    .tooltip('Kalos League')
    .unstackable()
    .fireResistant(true)

    event.create('rumble_badge')
    .texture('kubejs:item/kalos/rumble_badge')
    .displayName('Rumble Badge')
    .tooltip('Kalos League')
    .unstackable()
    .fireResistant(true)

    event.create('plant_badge')
    .texture('kubejs:item/kalos/plant_badge')
    .displayName('Plant Badge')
    .tooltip('Kalos League')
    .unstackable()
    .fireResistant(true)

    event.create('voltage_badge')
    .texture('kubejs:item/kalos/voltage_badge')
    .displayName('Voltage Badge')
    .tooltip('Kalos League')
    .unstackable()
    .fireResistant(true)

    event.create('fairy_badge')
    .texture('kubejs:item/kalos/fairy_badge')
    .displayName('Fairy Badge')
    .tooltip('Kalos League')
    .unstackable()
    .fireResistant(true)

    event.create('psychic_badge')
    .texture('kubejs:item/kalos/psychic_badge')
    .displayName('Psychic Badge')
    .tooltip('Kalos League')
    .unstackable()
    .fireResistant(true)

    event.create('iceberg_badge')
    .texture('kubejs:item/kalos/iceberg_badge')
    .displayName('Iceberg Badge')
    .tooltip('Kalos League')
    .unstackable()
    .fireResistant(true)

    // Galar League
    event.create('sas_grass_badge')
    .texture('kubejs:item/galar/grass_badge')
    .displayName('Grass Badge')
    .tooltip('Galar League')
    .unstackable()
    .fireResistant(true)

    event.create('sas_water_badge')
    .texture('kubejs:item/galar/water_badge')
    .displayName('Water Badge')
    .tooltip('Galar League')
    .unstackable()
    .fireResistant(true)

    event.create('sas_fire_badge')
    .texture('kubejs:item/galar/fire_badge')
    .displayName('Fire Badge')
    .tooltip('Galar League')
    .unstackable()
    .fireResistant(true)

    event.create('sas_fighting_badge')
    .texture('kubejs:item/galar/fighting_badge')
    .displayName('Fighting Badge')
    .tooltip('Galar League\nT1 FIGHTING!')
    .unstackable()
    .fireResistant(true)

    event.create('sas_ghost_badge')
    .texture('kubejs:item/galar/ghost_badge')
    .displayName('Ghost Badge')
    .tooltip('Galar League')
    .unstackable()
    .fireResistant(true)

    event.create('sas_fairy_badge')
    .texture('kubejs:item/galar/fairy_badge')
    .displayName('Fairy Badge')
    .tooltip('Galar League')
    .unstackable()
    .fireResistant(true)

    event.create('sas_rock_badge')
    .texture('kubejs:item/galar/rock_badge')
    .displayName('Rock Badge')
    .tooltip('Galar League')
    .unstackable()
    .fireResistant(true)

    event.create('sas_ice_badge')
    .texture('kubejs:item/galar/ice_badge')
    .displayName('Ice Badge')
    .tooltip('Galar League')
    .unstackable()
    .fireResistant(true)

    event.create('sas_dark_badge')
    .texture('kubejs:item/galar/dark_badge')
    .displayName('Dark Badge')
    .tooltip('Galar League')
    .unstackable()
    .fireResistant(true)

    event.create('sas_dragon_badge')
    .texture('kubejs:item/galar/dragon_badge')
    .displayName('Dragon Badge')
    .tooltip('Galar League')
    .unstackable()
    .fireResistant(true)

    // Paldea League
    // Gym
    event.create('sv_bug_badge')
    .texture('kubejs:item/paldea/svbadge_victoryroad_bug')
    .displayName('Bug Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_grass_badge')
    .texture('kubejs:item/paldea/svbadge_victoryroad_grass')
    .displayName('Grass Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_electric_badge')
    .texture('kubejs:item/paldea/svbadge_victoryroad_electric')
    .displayName('Electric Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_water_badge')
    .texture('kubejs:item/paldea/svbadge_victoryroad_water')
    .displayName('Water Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_normal_badge')
    .texture('kubejs:item/paldea/svbadge_victoryroad_normal')
    .displayName('Normal Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_ghost_badge')
    .texture('kubejs:item/paldea/svbadge_victoryroad_ghost')
    .displayName('Ghost Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_psychic_badge')
    .texture('kubejs:item/paldea/svbadge_victoryroad_psychic')
    .displayName('Psychic Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_ice_badge')
    .texture('kubejs:item/paldea/svbadge_victoryroad_ice')
    .displayName('Ice Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)
    
    // Starfall Street
    event.create('sv_dark_badge')
    .texture('kubejs:item/paldea/svbadge_starfallstreet_dark')
    .displayName("Dark Badge")
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_fire_badge')
    .texture('kubejs:item/paldea/svbadge_starfallstreet_fire')
    .displayName("Fire Badge")
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_poison_badge')
    .texture('kubejs:item/paldea/svbadge_starfallstreet_poison')
    .displayName('Poison Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_fairy_badge')
    .texture('kubejs:item/paldea/svbadge_starfallstreet_fairy')
    .displayName('Fairy Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_fighting_badge')
    .texture('kubejs:item/paldea/svbadge_starfallstreet_fighting')
    .displayName('Fighting Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    // Titan
    event.create('sv_rock_badge')
    .texture('kubejs:item/paldea/svbadge_pathoflegends_rock')
    .displayName('Rock Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_flying_badge')
    .texture('kubejs:item/paldea/svbadge_pathoflegends_flying')
    .displayName('Flying Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_steel_badge')
    .texture('kubejs:item/paldea/svbadge_pathoflegends_steel')
    .displayName('Steel Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_ground_badge')
    .texture('kubejs:item/paldea/svbadge_pathoflegends_ground')
    .displayName('Ground Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)

    event.create('sv_dragon_badge')
    .texture('kubejs:item/paldea/svbadge_pathoflegends_dragon')
    .displayName('Dragon Badge')
    .tooltip('Paldea League')
    .unstackable()
    .fireResistant(true)
  })
  